#
# Copyright 2022 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Verify examples using policy-tester

on:
  workflow_dispatch:
  push:
    branches: ['main', 'release-*']
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      GOPATH: ${{ github.workspace }}
      COSIGN_EXPERIMENTAL: 1

    steps:
    - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
      with:
        go-version: '1.18'
        check-latest: true

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        path: ./src/github.com/${{ github.repository }}
        fetch-depth: 0

    - name: Build the policy-tester CLI
      working-directory: ./src/github.com/${{ github.repository }}
      run: |
        make policy-tester

    - name: Install cosign
      uses: sigstore/cosign-installer@b3413d484cc23cf8778c3d2aa361568d4eb54679 # v2.5.0

    - name: Setup local registry
      run: |
        docker run -d  --restart=always \
          --name registry.local \
          -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 \
          -p 5000:5000 \
          registry:2

    - name: Example (custom-key-attestation-sbom-spdxjson)
      working-directory: ./src/github.com/${{ github.repository }}/examples
      run: |
        REF="localhost:5000/examples/custom-key-attestation-sbom-spdxjson"

        # Push an image
        docker pull alpine
        docker tag alpine "${REF}"
        docker push "${REF}"

        # Attach attestation to image
        cosign attest --yes --type spdxjson \
          --predicate sboms/example.spdx.json \
          --key keys/cosign.key \
          "${REF}"

        # Verify the attestation
        cosign verify-attestation \
          --type spdxjson \
          --key keys/cosign.pub \
          "${REF}"

        # Ensure the image satisfies the policy
        ../policy-tester \
          --policy policies/custom-key-attestation-sbom-spdxjson.yaml \
          --image "${REF}"

    # This example requires public Fulcio, only run on push to main
    - if: ${{ github.event_name == 'push' }}
      name: Example (keyless-attestation-sbom-spdxjson)
      working-directory: ./src/github.com/${{ github.repository }}/examples
      run: |
        REF="localhost:5000/examples/keyless-attestation-sbom-spdxjson"

        # Push an image
        docker pull alpine
        docker tag alpine "${REF}"
        docker push "${REF}"

        # Attach attestation to image
        cosign attest --yes --type spdxjson \
          --predicate sboms/example.spdx.json \
          "${REF}"

        # Ensure the image satisfies the policy
        ../policy-tester \
          --policy policies/keyless-attestation-sbom-spdxjson.yaml \
          --image "${REF}"

    # This example requires public Fulcio, only run on push to main
    - if: ${{ github.event_name == 'push' }}
      name: Example (signed-by-github-actions)
      working-directory: ./src/github.com/${{ github.repository }}/examples
      run: |
        REF="localhost:5000/examples/signed-by-github-actions"

        # Push an image
        docker pull alpine
        docker tag alpine "${REF}"
        docker push "${REF}"

        # Sign image
        cosign sign "${REF}"

        # Ensure the image satisfies the policy
        ../policy-tester \
          --policy policies/signed-by-github-actions.yaml \
          --image "${REF}"
